import type { ProfessionalContent } from "./professional";

export const professionalContent: ProfessionalContent = {
	identity: {
		name: "Davi Naizer Santos",
		headline: "Senior Frontend & Product Engineer",
		location: "Hove, United Kingdom",
		profileLinks: [
			{
				label: "LinkedIn",
				url: "https://www.linkedin.com/in/davi-naizer",
			},
			{
				label: "GitHub",
				url: "https://github.com/davinaizer",
			},
		],
	},
	summary: {
		summary:
			"Senior frontend and product engineer with experience building product applications, internal tools, and the engineering systems behind them. My commercial experience centres on React, TypeScript, and JavaScript, alongside recent native iOS development with Swift and SwiftUI.",
		homeExcerpt:
			"Senior frontend and product engineer who builds product experiences and improves the systems around them. My work centres on understanding workflows, reducing recurring friction, and making software easier to build, maintain, and use, with commercial experience in React and TypeScript and recent native iOS development in SwiftUI.",
		focusAreas: [
			"Frontend architecture",
			"Product development",
			"Developer tooling",
			"Workflow automation",
			"Engineering practices",
		],
	},
	experience: [
		{
			slug: "independent-product-venture-product-engineer-co-creator-2025",
			company: "Independent Product Project",
			role: "Product Engineer & Co-creator",
			startDate: "12/2025",
			responsibilities: [
				"Building Alfred with a backend engineer as an independent side project intended to continue alongside our professional work. The product helps people capture ideas, receive recommendations and turn them into practical plans. I lead development of the native iOS application while sharing responsibility for product direction, application architecture and technical decisions. The application is currently undergoing private TestFlight validation ahead of its first public release.",
			],
			contributions: [
				"Built the native iOS application from the ground up, delivering the first end-to-end product experience across onboarding, authentication, recommendations and planning workflows.",
				"Designed the application's layered architecture using MVVM-style presentation, repositories, use cases and dependency injection to keep business logic decoupled, testable and maintainable.",
				"Worked closely with the backend engineer to shape product workflows, technical decisions and application architecture throughout development.",
				"Integrated backend services for authentication, real-time updates, deep linking and application state while maintaining clear boundaries between networking, domain logic and presentation.",
				"Developed reusable, accessible UI components with consistent theming and Dynamic Type support, making the interface easier to build, maintain and evolve.",
				"Added automated tests across the presentation, domain, data and infrastructure layers, focusing on business logic and application behaviour rather than UI interactions.",
				"Standardised project configuration, build tooling and repository workflows using XcodeGen and automated verification.",
				"Established an AI-assisted engineering workflow combining code generation with architectural review, testing and manual verification before changes are accepted.",
			],
			technologies: [
				"Swift",
				"SwiftUI",
				"REST APIs",
				"Firebase",
				"XCTest",
				"XcodeGen",
				"GitLab",
			],
		},
		{
			slug: "self-employed-planned-career-break-2024-2025",
			company: "Self-employed",
			role: "Planned Career Break",
			startDate: "11/2024",
			endDate: "11/2025",
			responsibilities: [
				"Took a planned break from full-time employment after leaving The Signal Group. During that time I stepped back to re-evaluate my career direction and returned to hands-on product development, which eventually developed into the venture behind Alfred.",
			],
			contributions: [],
			technologies: [],
		},
		{
			slug: "signal-group-senior-frontend-software-engineer-2023-2024",
			company: "The Signal Group",
			role: "Senior Frontend Software Engineer",
			startDate: "12/2023",
			endDate: "10/2024",
			location: "London, UK",
			responsibilities: [
				"Worked on Signal Ocean, a maritime intelligence platform used by brokers, operators and analysts to monitor global shipping activity. As part of a cross-functional product team, I worked on the Vessel List area within a large React and TypeScript monorepo. One recurring challenge was that creating reusable Vessel List templates required support requests and manual engineering work. We redesigned that workflow into a self-service experience that allowed company administrators to create and manage templates directly.",
			],
			contributions: [
				"Developed the frontend implementation of the Template Admin experience, taking the feature through implementation, testing, fixes and production release.",
				"Implemented role-based template management for a multi-company SaaS platform, separating administrator management capabilities from end-user template consumption.",
				"Built data-intensive configuration workflows using AG Grid, including role-based editing, validation, read-only and deletion states, and reusable editing behaviours.",
				"Worked closely with backend engineers on metadata-driven APIs and shared application state to support reusable template configuration across multiple dashboards.",
				"Developed React and TypeScript features across the Vessel List area and shared UI component library.",
				"Onboarded a frontend engineer to the monorepo, Vessel List architecture and Azure-based development environment.",
			],
			technologies: [
				"React",
				"TypeScript",
				"MobX",
				"OpenLayers",
				"AG Grid",
				"C#",
				".NET",
				"Azure DevOps",
				"REST APIs",
			],
		},
		{
			slug: "ballys-interactive-frontend-tech-lead-2022-2023",
			company: "Bally's Interactive",
			role: "Frontend Tech Lead",
			startDate: "11/2022",
			endDate: "11/2023",
			location: "London, UK",
			responsibilities: [
				"Provided technical direction across frontend initiatives focused on code quality, developer experience, onboarding and platform modernisation. Worked with Product, Technical Architects and engineering teams to improve frontend architecture, engineering standards and delivery practices across multiple products.",
			],
			contributions: [
				"Defined a frontend code-quality standardisation programme covering 13 frameworks, tools and shared libraries, introducing consistent linting, formatting, commit validation, Pull Request automation and static analysis.",
				"Integrated SonarQube with GitHub Actions and Pull Request decoration, investigating monorepo test-reporting issues affecting quality-gate adoption.",
				"Mapped dependencies and technical debt across the BMC reward-component architecture, identifying duplicated logic, legacy constraints and reusable abstractions to guide modernisation.",
				"Created a structured onboarding programme covering repositories, architecture, production workflows and developer setup, including automated repository discovery through Confluence.",
				"Provided technical direction during roadmap planning, refinement and delivery, helping define technical stories and prioritise platform improvements alongside product work.",
			],
			technologies: [
				"React",
				"TypeScript",
				"Redux Toolkit",
				"Nx",
				"GitHub Actions",
				"SonarQube",
				"Jenkins",
				"Storybook",
				"Node.js",
				"GitHub Enterprise REST APIs",
			],
		},
		{
			slug: "gamesys-ballys-senior-frontend-engineer-2020-2022",
			company: "Gamesys / Bally's Interactive",
			role: "Senior Frontend Engineer",
			startDate: "10/2020",
			endDate: "11/2022",
			location: "London, UK",
			responsibilities: [
				"Worked across customer-facing products and internal engineering tooling, increasingly focusing on developer experience, workflow automation and frontend platform improvements.",
			],
			contributions: [
				"Built a Node.js tool around the Jira REST API that reduced a promotional content workflow from days to minutes.",
				"Developed reusable tooling around the GitHub Enterprise REST API that removed the need to clone repositories for deployment-related tasks.",
				"Built internal tooling supporting Offer Builder, promotional content generation, deployment and day-to-day engineering workflows.",
				"Created onboarding guides, architecture documentation and dependency maps that helped engineers understand large projects more quickly.",
				"Supported the team through mentoring, code reviews and production troubleshooting.",
			],
			technologies: [
				"React",
				"JavaScript",
				"Styled-components",
				"Node.js",
				"Redux",
				"GitHub REST API",
				"Jenkins",
				"Jira REST API",
			],
		},
		{
			slug: "gamesys-frontend-developer-2019-2020",
			company: "Gamesys",
			role: "Frontend Developer",
			startDate: "03/2019",
			endDate: "09/2020",
			location: "London, UK",
			responsibilities: [
				"Joined the Promotions team building customer-facing promotional experiences before expanding into frontend architecture, developer tooling and cross-team enablement.",
			],
			contributions: [
				"Led the technical improvement initiative for Landing Pages, defining the proposed frontend architecture, documenting the roadmap and presenting the approach to engineering, QA, design and business stakeholders.",
				"Built reusable frontend components and styling foundations to improve consistency across promotional interfaces.",
				"Developed GitHub API-based deployment tooling that simplified deployment workflows and reduced reliance on repository cloning.",
				"Mentored developers, designers and stakeholders through code reviews, frontend debugging, Git support and technical documentation.",
				"Contributed to customer-facing React applications while helping improve internal engineering tooling and workflows.",
			],
			technologies: [
				"React",
				"JavaScript",
				"Redux",
				"Webpack",
				"Sass",
				"Node.js",
			],
		},
		{
			slug: "unbox-learning-experience-co-founder-technical-lead-2009-2017",
			company: "UNBOX Learning Experience",
			role: "Co-founder & Technical Lead",
			startDate: "2009",
			endDate: "2017",
			location: "Brazil",
			responsibilities: [
				"Co-founded a digital learning company developing e-learning platforms, Learning Management Systems (LMS) and interactive educational products for Fortune 500 and global enterprise clients, including Volvo Brasil, Grupo Boticário, MetLife and HSBC. Worked across product discovery, solution design, technical leadership, frontend development and client delivery while coordinating a multidisciplinary team of designers and developers.",
			],
			contributions: [
				"Worked directly with clients, designers and instructional specialists to translate business and learning requirements into practical software solutions.",
				"Led technical delivery of client projects, coordinating a team of up to five developers while remaining hands-on with architecture, frontend development and implementation.",
				"Reduced e-learning delivery time from around three months to four weeks by developing a reusable framework and improving the end-to-end process across discovery, instructional design, UX, development and quality assurance.",
				"Built browser-based learning platforms, interactive educational products and custom Learning Management System (LMS) functionality for enterprise projects.",
			],
			technologies: ["JavaScript", "HTML", "CSS", "ActionScript", "Moodle"],
		},
	],
	claims: [],
	resume: {
		label: "Download Resume",
		url: "/resume.pdf",
		updatedAt: "2026-09-15",
	},
	contact: [
		{
			label: "Email",
			url: "mailto:davi.naizer@gmail.com",
			category: "Direct",
			actionLabel: "Send an email",
			description: "Professional opportunities and collaboration.",
		},
		{
			label: "LinkedIn",
			url: "https://www.linkedin.com/in/davi-naizer",
			category: "Professional profile",
			actionLabel: "View LinkedIn profile",
			description: "Career history and professional background.",
		},
	],
};
